### ISSUE TITLE
Adding Pokémon doesn't change the Exefs

### ISSUE THREAD

**Issue by XModxGodX** [Nifyr/Imposters-Ordeal#13]
When adding a new Pokémon it gives the disclaimer that it needs to edit the exefs to work properly but it only outputs the romfs and when testing it the Pokémon is named egg in battle and crashes when catching it. Specially on SP 1.3.0 using atmosphere.

**Comment by Nifyr** [comment]
Pokédex expansion requires engine changes (on the exefs portion of the rom) to work propery, and is thus outside the scope of this application.

**Comment by Nifyr** [comment]
This unfortunately means that you can't add extra slots for pokémon if you can't procure an appropriate patch. For now, it is mainly just useful for developers
