### ISSUE TITLE
Feature Request: Replace Forms/ Pokemon with other Forms/ Pokemon

### ISSUE THREAD

**Issue by XModxGodX** [Nifyr/Imposters-Ordeal#14]
The main reason I want this feature is so I don't have to deal with sky form Shaymin reverting at night. Even adding a new form for Shaymin makes it revert to land form at night.

**Comment by Nifyr** [comment]
A feature letting one replace forms or species is unlikely to be implemented. As for your use case, you'd ideally want to solve this with an exefs patch. It is possible to do a replacement as a workaround, though it will need to be done manually.
