### ISSUE TITLE
Feature Request: Battle Tower Trainer editor

### ISSUE THREAD

**Issue by TheZoroark007** [Nifyr/Imposters-Ordeal#17]
Would it be possible to add an additional trainer editor that works with the battle tower trainers ? This would be helpful for projects with a national dex like Luminescent Platinum in the future to add national dex mons to the roster. The structure of the individual trainers is quiet similar to that one of normal trainers, but slightly different.
I did a writeup on how the battle tower handles trainers and Pokemon a while ago here:
https://docs.google.com/document/d/1Emvyh12wuLOp3oZRIefG1aGjFVWuWttc/edit?usp=sharing&ouid=115306775996833955169&rtpof=true&sd=true

**Comment by TheZoroark007** [comment]
I started implementing it myself for now. The editor for the tower Pokemon works already, the part for changing which trainer gets which Pokemon will be implemented soon

**Comment by Nifyr** [comment]
By all means, feel free to fork the repo and create a pull request!
