### ISSUE TITLE
Randomization method

### ISSUE THREAD

**Issue by patrickgra** [Nifyr/Imposters-Ordeal#18]
Am I right in the assumption that the randomization is done by a 1 to 1 mapping? At least my shops were nearly identical and I encountered the same Pokemon quite often.
Is it possible to randomize each encounter individually?

**Comment by Nifyr** [comment]
You appear to have randomized with the default settings, which is set to place stuff in the game with the same rate as they appear in vanilla BDSP. You can adjust this probability distributon and any others by clicking on their corresponding button:
![image](https://user-images.githubusercontent.com/34029571/230773982-f5d5b1ea-bffc-419c-912e-73152a7a124e.png)
It will open up a config for this option's distribution:
![image](https://user-images.githubusercontent.com/34029571/230774339-0797df2a-cb47-4382-9273-e5f71db7095a.png)
By default it'll be set to empirical, pre-loaded with the rates found in your dump. As we can see, lots of Zubats and Golbats, just like in normal BDSP. If you don't want that, however, and just want each pokémon to be selected with equal likelyhood, there's an option for that! Select uniform mode:
![image](https://user-images.githubusercontent.com/34029571/230774705-d275ca2b-2ae2-4e8a-a27f-d99b56429533.png)
And now, every pokémon with a checkmark here will have an equal rate of appearing in your game!
![image](https://user-images.githubusercontent.com/34029571/230774906-ce1a96d2-814d-400a-85e4-b4dae0ffdaee.png)

Imposter's Ordeal has no options for redistribution or 1 to 1 mapping as you describe. Hopefully this answers your questions.
