### ISSUE TITLE
Not all TMs visible when editing Pokemon

### ISSUE THREAD

**Issue by MasterDriverRex** [Nifyr/Imposters-Ordeal#19]
I'm currently doing some Pokemon editing, using the data from Luminescent Platinum, and for some reason TMs 32, 42, 44, 45, 58, 82, 87, 90 are not showing up in the TM list, meaning I can't deselect or select them.

![Imposter's Ordeal TM issue](https://user-images.githubusercontent.com/53700965/230867175-813c43b5-7e02-451e-85c9-cd42bba82c95.png)

**Comment by Nifyr** [comment]
This is not a bug. To my knowledge, Luminescent Platinum edits what TM compatibility sets each TM uses, with some ending up sharing the same compatibility set. This doesn't mash very well with the pokémon editor as it won't display some of the TMs' names. You can still edit their compatibility, however, as every compatibility set is listed. Imposter's Ordeal has a TM editor that you can use to check and swap out compatibility sets.
