### ISSUE TITLE
App keeps asking to install .NET

### ISSUE THREAD

**Issue by svnv-svsv-jm** [Nifyr/Imposters-Ordeal#22]
I have .NET 5.0 Framework installed. I click on the `.exe` file, a prompt wanrs me to install it again. I click, I do it, and the loop continues. The error went away after I re-built the app with .NET 7.0, but now a new error appears...

**Comment by Nifyr** [comment]
.NET Framework is something else, and evidently .NET 7 isn't sufficient... Did you try downloading the .NET 5.0 desktop runtime? [https://dotnet.microsoft.com/en-us/download/dotnet/5.0](https://dotnet.microsoft.com/en-us/download/dotnet/5.0)

**Comment by svnv-svsv-jm** [comment]
Yes.
