### ISSUE TITLE
Shiny rate wont change

### ISSUE THREAD

**Issue by GottesGamer** [Nifyr/Imposters-Ordeal#27]
Hi Nifyr,

i hope your still active. I found your Program and love it. But everytime i try to change the Shiny rate nothing happens. I even used 100% to see if it is active but all Pokemon are still normal. Is there anyway to change it? Even if i check the Box random shinies it doesnt change anything. I hope you can help me out :)

**Comment by georgefarrell24-gif** [comment]
Hey did you get an answer for this, would love to increase shiny odds for encounters
