### ISSUE TITLE
Type Matchup Editor Window is cutout

### ISSUE THREAD

**Issue by onesliced** [Nifyr/Imposters-Ordeal#5]
The window for Type Matchup Editor doesn't show a fully, the bottom part is being cut out, also the attack type doesn't align properly with the cell in the right side. 
I'm using v2.9.2, windows 10, resolution 1366x768.

![Type Window error](https://user-images.githubusercontent.com/106728067/171575127-6dc77330-e536-45ab-8a40-a6475463d4c5.png)

**Comment by Nifyr** [comment]
Oops, maybe having the window fixed at that size isn't ideal... I've made the editor smaller and resizable in release v2.9.3, so do confirm if that solves the issue for you.

**Comment by onesliced** [comment]
> Oops, maybe having the window fixed at that size isn't ideal... I've made the editor smaller and resizable in release v2.9.3, so do confirm if that solves the issue for you.

It's show fully now but it looks like this when it's first opened :
(Only when I resized manually that the cells become aligned properly.)

![Type Window error 2](https://user-images.githubusercontent.com/106728067/172036392-e3c4fd97-ae5f-4ffb-b2e0-ff2fe579183f.png)

**Comment by Nifyr** [comment]
That's good enough for me.
