### ISSUE TITLE
wild mon editor's rate can't be changed

### ISSUE THREAD

**Issue by leineg** [Nifyr/Imposters-Ordeal#9]
I'm trying to change the rate of wild encounters but I double click it and does nothing, is it a bug or you can't change the % of rate?

**Comment by Nifyr** [comment]
The rates in the encounter table editor are only displayed for the sake of convenience. You cannot change them in Imposters Ordeal. These rates are hard-coded and would require making changes to the game's executable (exefs) to change. Luckily, through combined usage of multiple encounter slots you can generally adjust any pokémon's rate to what you'd want them to be.

**Comment by leineg** [comment]
one more thing how do i change the swarm encounters?
